#!/usr/bin/env python3
"""Validate and export task scopes from the Amazon ASIN registry."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any


REGISTRY_FILE = Path(__file__).with_name("amazon_asin_registry.json")
ASIN_PATTERN = re.compile(r"^[A-Z0-9]{10}$")


def load_registry(path: Path = REGISTRY_FILE) -> dict[str, Any]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if data.get("schema_version") != 1:
        raise ValueError(f"Unsupported registry schema: {data.get('schema_version')!r}")

    segments = data.get("segments")
    tasks = data.get("tasks")
    if not isinstance(segments, list) or not isinstance(tasks, dict):
        raise ValueError("Registry must contain segments[] and tasks{}")

    segment_ids: set[str] = set()
    asin_owner: dict[str, str] = {}
    for segment in segments:
        segment_id = segment.get("id")
        asins = segment.get("asins")
        if not isinstance(segment_id, str) or not segment_id:
            raise ValueError("Each segment needs a non-empty id")
        if segment_id in segment_ids:
            raise ValueError(f"Duplicate segment id: {segment_id}")
        segment_ids.add(segment_id)
        if not isinstance(asins, list) or not asins:
            raise ValueError(f"Segment {segment_id} has no ASINs")
        for asin in asins:
            if not isinstance(asin, str) or not ASIN_PATTERN.fullmatch(asin):
                raise ValueError(f"Invalid ASIN in segment {segment_id}: {asin!r}")
            previous = asin_owner.get(asin)
            if previous:
                raise ValueError(f"ASIN {asin} is duplicated in {previous} and {segment_id}")
            asin_owner[asin] = segment_id

    for task_id, task in tasks.items():
        if not isinstance(task, dict):
            raise ValueError(f"Task {task_id} must be an object")
        for segment_id in task.get("segments", []):
            if segment_id not in segment_ids:
                raise ValueError(f"Task {task_id} references unknown segment: {segment_id}")
        for asin in task.get("asins", []):
            if asin not in asin_owner:
                raise ValueError(f"Task {task_id} references unregistered ASIN: {asin}")
        task_asins(data, task_id)

    return data


def _segment_map(registry: dict[str, Any]) -> dict[str, dict[str, Any]]:
    return {segment["id"]: segment for segment in registry["segments"]}


def task_asins(registry: dict[str, Any], task_id: str) -> list[str]:
    task = registry.get("tasks", {}).get(task_id)
    if task is None:
        raise KeyError(f"Unknown task: {task_id}")

    segment_map = _segment_map(registry)
    ordered: list[str] = []
    seen: set[str] = set()
    for segment_id in task.get("segments", []):
        for asin in segment_map[segment_id]["asins"]:
            if asin not in seen:
                ordered.append(asin)
                seen.add(asin)
    for asin in task.get("asins", []):
        if asin not in seen:
            ordered.append(asin)
            seen.add(asin)
    if not ordered:
        raise ValueError(f"Task {task_id} resolves to an empty ASIN list")
    return ordered


def get_task_asins(task_id: str, path: Path = REGISTRY_FILE) -> list[str]:
    return task_asins(load_registry(path), task_id)


def render_task_asins(registry: dict[str, Any], task_id: str) -> str:
    task = registry["tasks"][task_id]
    segment_map = _segment_map(registry)
    lines = [
        "# AUTO-GENERATED from /Users/lihuan/ai-workspace/workflows/amazon_asin_registry.json",
        f"# Task: {task_id} | {task.get('label', task_id)}",
        "# Do not edit this file directly; edit the registry and re-export.",
    ]
    if task.get("segments"):
        for segment_id in task["segments"]:
            segment = segment_map[segment_id]
            lines.extend(["", f"# {segment['label']} ({segment['role']})"])
            lines.extend(segment["asins"])
    else:
        lines.extend(["", *task_asins(registry, task_id)])
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=["validate", "list", "export"])
    parser.add_argument("--task", choices=["weekly_listing", "daily_price"])
    parser.add_argument("--output", type=Path)
    parser.add_argument("--registry", type=Path, default=REGISTRY_FILE)
    args = parser.parse_args()

    registry = load_registry(args.registry)
    if args.command == "validate":
        counts = {task_id: len(task_asins(registry, task_id)) for task_id in registry["tasks"]}
        print(json.dumps({"valid": True, "registered": sum(len(s["asins"]) for s in registry["segments"]), "tasks": counts}, ensure_ascii=False))
        return 0

    if not args.task:
        parser.error("--task is required for list/export")
    if args.command == "list":
        print("\n".join(task_asins(registry, args.task)))
        return 0
    if not args.output:
        parser.error("--output is required for export")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_task_asins(registry, args.task), encoding="utf-8")
    print(f"exported {len(task_asins(registry, args.task))} ASINs to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
